feat: updates package versions
defi-wonderland/solidity-boilerplate pull request #9
Opened 2021-08-09 01:40 UTC by 404skillz

Hardhat can not be upgraded, since it will start returning an error on the tests.
![image](https://user-images.githubusercontent.com/83831549/128652784-84cb56e2-71b1-4786-b205-bf58a0d482d5.png)

2021-08-09 19:03 UTC, 0xGorilla commented
please revert all the changes in types back to typechained

2021-08-09 19:04 UTC, 0xGorilla requested changes
Please revert typechain changes to output to typechained again

2021-08-10 22:34 UTC, enderman0x approved these changes

2021-08-11 10:04 UTC, 0xGorilla approved these changes
:clap: to the smock implementation

2021-09-12 20:48 UTC, merged